In [2]:
# Import OpenCV2 for image processing
import cv2

# Start capturing video 
vid_cam = cv2.VideoCapture(0)

# Detect object in video stream using Haarcascade Frontal Face
face_detector = cv2.CascadeClassifier('C:\\Users\\hp pc\\Downloads\\Raspberry-Face-Recognition-master (1)\\Raspberry-Face-Recognition-master\\haarcascade_frontalface_default.xml')

# For each person, one face id
face_id =1

# Initialize sample face image
count = 0

# Start looping
while(True):

    # Capture video frame
    _, image_frame = vid_cam.read()

    # Convert frame to grayscale
    gray = cv2.cvtColor(image_frame, cv2.COLOR_BGR2GRAY)

    # Detect frames of different sizes, list of faces rectangles
    faces = face_detector.detectMultiScale(gray, 1.3, 5)

    # Loops for each faces
    for (x,y,w,h) in faces:

        # Crop the image frame into rectangle
        cv2.rectangle(image_frame, (x,y), (x+w,y+h), (255,0,0), 2)
        
        # Increment sample face image
        count += 1

        # Save the captured image into the datasets folder
        cv2.imwrite("C:\\Users\\hp pc\\Downloads\\dataset\\" + str(face_id) + '.' + str(count) + ".jpg", gray[y:y+h,x:x+w])

        # Display the video frame, with bounded rectangle on the person's face
        cv2.imshow('frame', image_frame)

    # To stop taking video, press 'q' for at least 100ms
    if cv2.waitKey(100) & 0xFF == ord('q'):
        break

    # If image taken reach 100, stop taking video
    elif count>=200:
        break

# Stop video
vid_cam.release()

# Close all started windows
cv2.destroyAllWindows()


In [3]:

# Import OpenCV2 for image processing
# Import os for file path
import cv2, os

# Import numpy for matrix calculation
import numpy as np

# Import Python Image Library (PIL)
from PIL import Image

# Create Local Binary Patterns Histograms for face recognization
recognizer = cv2.face.LBPHFaceRecognizer_create()

# Using prebuilt frontal face training model, for face detection
detector = cv2.CascadeClassifier("C:\\Users\\hp pc\\Downloads\\Raspberry-Face-Recognition-master (1)\\Raspberry-Face-Recognition-master\\haarcascade_frontalface_default.xml");

# Create method to get the images and label data
def getImagesAndLabels(path):

    # Get all file path
    imagePaths = [os.path.join(path,f) for f in os.listdir(path)] 
    
    # Initialize empty face sample
    faceSamples=[]
    
    # Initialize empty id
    ids = []

    # Loop all the file path
    for imagePath in imagePaths:

        # Get the image and convert it to grayscale
        PIL_img = Image.open(imagePath).convert('L')

        # PIL image to numpy array
        img_numpy = np.array(PIL_img,'uint8')

        # Get the image id
        id = int(os.path.split(imagePath)[-1].split(".")[0])
        print(id)

        # Get the face from the training images
        faces = detector.detectMultiScale(img_numpy)
        print(faces)

        # Loop for each face, append to their respective ID
        for (x,y,w,h) in faces:

            # Add the image to face samples
            faceSamples.append(img_numpy[y:y+h,x:x+w])

            # Add the ID to IDs
            ids.append(id)

    # Pass the face array and IDs array
    return faceSamples,ids

# Get the faces and IDs
faces,ids = getImagesAndLabels('C:\\Users\\hp pc\\Downloads\\dataset\\')

# Train the model using the faces and IDs
recognizer.train(faces, np.array(ids))

# Save the model into trainer.yml
recognizer.save('E:\\trainer.yml')


1
[[ 19  19 224 224]]
1
[[ 13  12 208 208]]
1
[[ 19  20 190 190]]
1
[[ 15  18 193 193]]
1
[[ 15  19 197 197]]
1
[[ 19  22 193 193]]
1
[[ 18  24 182 182]]
1
[[ 12  10 191 191]]
1
[[ 15  16 193 193]]
1
[[ 27  16 192 192]]
1
[[ 17  16 193 193]]
1
[[ 23  19 198 198]]
1
[[ 13  12 201 201]]
1
[[ 16  12 184 184]]
1
[[ 16  17 190 190]]
1
[[ 16  18 197 197]]
1
[[ 22  14 200 200]]
1
[[ 19  12 197 197]]
1
[[ 30  16 189 189]]
1
[[ 21  15 198 198]]
1
[[ 26  19 197 197]]
1
[[ 22  19 196 196]]
1
[[ 23  18 192 192]]
1
[[  9  11 205 205]]
1
[[ 30  19 187 187]]
1
[[ 23  15 192 192]]
1
[[ 21  16 191 191]]
1
[[ 24  16 198 198]]
1
[[ 22  20 191 191]]
1
[[ 22  16 193 193]]
1
[[ 28  21 189 189]]
1
[[ 30  22 188 188]]
1
[[ 25  19 190 190]]
1
[[ 27  21 184 184]]
1
[[ 17  14 197 197]]
1
()
1
[[ 18  19 198 198]]
1
[[ 23  14 192 192]]
1
[[ 15  11 190 190]]
1
[[ 20  15 189 189]]
1
[[ 15  12 193 193]]
1
[[ 22  17 194 194]]
1
[[ 27  19 191 191]]
1
[[ 25  16 195 195]]
1
[[ 23  14 193 193]]
1
[[ 18  20 193 193]]
1
[[ 

In [1]:
# Import OpenCV2 for image processing
import cv2

# Import numpy for matrices calculations
import numpy as np

# Create Local Binary Patterns Histograms for face recognization
recognizer = cv2.face.LBPHFaceRecognizer_create()

# Load the trained mode
recognizer.read('E:\\trainer.yml')

# Load prebuilt model for Frontal Face
cascadePath = "C:\\Users\\hp pc\\Downloads\\Raspberry-Face-Recognition-master (1)\\Raspberry-Face-Recognition-master\\haarcascade_frontalface_default.xml"

# Create classifier from prebuilt model
faceCascade = cv2.CascadeClassifier(cascadePath);

# Set the font style
font = cv2.FONT_HERSHEY_SIMPLEX

# Initialize and start the video frame capture
cam = cv2.VideoCapture(0)

# Loop
while True:
    # Read the video frame
    ret, im =cam.read()

    # Convert the captured frame into grayscale
    gray = cv2.cvtColor(im,cv2.COLOR_BGR2GRAY)

    # Get all face from the video frame
    faces = faceCascade.detectMultiScale(gray, 1.2,5)

    # For each face in faces
    for(x,y,w,h) in faces:

        # Create rectangle around the face
        cv2.rectangle(im, (x-20,y-20), (x+w+20,y+h+20), (0,255,0), 4)

        # Recognize the face belongs to which ID
        Id = recognizer.predict(gray[y:y+h,x:x+w])

        # Check the ID if exist 
        if(Id == 2):
            Id = "harish"
            print(Id)
        #If not exist, then it is Unknown
        elif(Id == 5):
            Id = "obama"
            print(Id)
        else:
            print(Id)
            Id = "Unknown"

        # Put text describe who is in the picture
        cv2.rectangle(im, (x-22,y-90), (x+w+22, y-22), (0,255,0), -1)
        cv2.putText(im, str(Id), (x,y-40), font, 2, (255,255,255), 3)

    # Display the video frame with the bounded rectangle
    cv2.imshow('im',im) 

    # If 'q' is pressed, close program
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break

# Stop the camera
cam.release()

# Close all windows
cv2.destroyAllWindows()


KeyboardInterrupt: 

In [5]:
# Import OpenCV2 for image processing
import cv2

# Import numpy for matrices calculations
import numpy as np

# Create Local Binary Patterns Histograms for face recognization
recognizer = cv2.face.LBPHFaceRecognizer_create()

# Load the trained mode
recognizer.read('E:\\trainer.yml')

# Load prebuilt model for Frontal Face
cascadePath = "C:\\Users\\hp pc\\Downloads\\Raspberry-Face-Recognition-master (1)\\Raspberry-Face-Recognition-master\\haarcascade_frontalface_default.xml"

# Create classifier from prebuilt model
faceCascade = cv2.CascadeClassifier(cascadePath);

# Set the font style
font = cv2.FONT_HERSHEY_SIMPLEX

# Initialize and start the video frame capture
cam = cv2.VideoCapture(0)

# Loop
while True:
    # Read the video frame
    ret, im =cam.read()

    # Convert the captured frame into grayscale
    gray = cv2.cvtColor(im,cv2.COLOR_BGR2GRAY)

    # Get all face from the video frame
    faces = faceCascade.detectMultiScale(gray, 1.2,5)

    # For each face in faces
    for(x,y,w,h) in faces:
        Id, conf = recognizer.predict(gray[y:y+h,x:x+w])
        cv2.rectangle(im,(x-50,y-50),(x+w+50,y+h+50),(225,0,0),2)
        if(Id==1):
             Id='Atul Sir'
        else:
             Id='Hariya'
        cv2.putText(im,str(Id)+"--"+str(conf), (x,y+h),font, 1.1, (0,255,0)) #Draw the text
        cv2.imshow('im',im)
        cv2.waitKey(10)

    # If 'q' is pressed, close program
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break

# Stop the camera
cam.release()

# Close all windows
cv2.destroyAllWindows()
